var TioranatTranslationBase = {
    "en": {
        "answers": {
            "age00": "0-20 years ",
            "age20": "20-40 years",
            "age40": "40-60 years",
            "age60": "60-80 years",
            "age80": "over 80 years",
            "day14ago": "more than 14 days ago",
            "day1ago": "within the last 24 hours",
            "day3ago": "within the last 7 days",
            "day7ago": "more than 7 days ago",
            "fever37": "no fever",
            "fever38": "a fever of 38° Celsius or higher",
            "fever39": "a fever of 39° Celsius or higher",
            "maybe": "maybe",
            "never": "never",
            "no": "no",
            "notsure": "unsure",
            "yes": "yes"
        },
        "questions": {
            "QuestionSmoker": "Do you smoke? ",
            "QuestionLung": "Do you have a medically confirmed lung disease?",
            "QuestionDiabetes": "Do you have diabetes?",
            "QuestionHeart": "Do you have a medically diagnosed heart disease?",
            "QuestionAdipositas": "Are you very overweight?",
            "QuestionPregnancy": "Are you pregnant?",
            "QuestionCortison": "Do you take cortisone?",
            "QuestionImunSuppressiva": "Do you take immunosuppressant drugs?",
            "QuestionInfluenzaVaccination": "Have you been vaccinated against influenza in the last few months?",
            "QuestionArticularRheumatism": "Have you been diagnosed with rheumatism?",
            "QuestionChemotherapy": "Are you currently undergoing chemotherapy?",
            "QuestionAge": "How old are you?",
            "QuestionContact": "When did you have contact with a person who tested positive for COVID-19?",
            "QuestionTravelDaysAgo": "Have you been to any of the risk areas recently?",
            "QuestionFeverLast24h": "Do you have a fever?",
            "QuestionFeverLast4d": "Have you had a fever in the last 4 days?",
            "QuestionChills": "Do you have chills?",
            "QuestionFatigue": "Are you feeling more fatigued than usual?",
            "QuestionBodyAches": "Do you have body aches?",
            "QuestionDryCough": "Do you have a persistent cough?",
            "QuestionRunnyNose": "Do you have more or different colds than usual?",
            "QuestionDiariah": "Do you have diarrhoea?",
            "QuestionSoreThroat": "Do you have a sore throat?",
            "QuestionHeadAche": "Do you have a headache?",
            "QuestionShortBreath": "Are you currently out of breath faster than usual?",
            "QuestionLossOfSmellTaste": "Do you experience a loss of smell and taste? ",
            "QuestionSneezing": "Do you have to sneeze?"
        },
        "details": {
            "DetailsQuestionContact": "A contact between people consists of an exchange of body fluids or having spent more than 15 minutes within 2 meters of each other."
        },
        "survey": {
            "LanguageName": "english",
            "BecomeTranslator": "Unfortunately the questionnaire is not yet available in this language. If you are able to translate texts from German\/English into your language then please contact us by _email_.",
            "HeadLine": "Patient self-assessment",
            "PreLanguageIntroduction": "Do you have a COVID-19 infection?  \\n\\nThis questionnaire helps you to assess your risk. Your information remains in the browser itself and is therefore private. You can use the results of this questionnaire in PDF format for a medical consultation.",
            "LanguageIntroduction": "Your details remain in the browser itself and are therefore private.",
            "DocumentIntroduction": "This questionnaire helps to assess your risk for COVID-19 infection. Use it as a guide for a doctor's consultation. ",
            "InfectionRiskHeader": "Symptoms and contact",
            "InfectionRiskDetails": "Your current health status in regard to factors which may pose an additional risk, when infected with the coronavirus COVID-19.",
            "InfectionRiskGreen": "It appears that you do not currently have any of the typical symptoms. However, if you feel unwell, call your doctor. Take good care of yourself and protect yourself and others.",
            "InfectionRiskYellow": "Take it easy and observe your symptoms. If they worsen or you are unsure, call your doctor.",
            "InfectionRiskRed": "Protect yourself and your fellow humans through isolation. Call your local advice centre. ",
            "RiskGroupHeader": "Risk Group",
            "RiskGroupDetails": "Your current health status in regard to factors which may pose an additional risk, when infected with the coronavirus COVID-19.",
            "RiskGroupGreen": "According to your assessment, you currently have no additional risks.",
            "RiskGroupYellow": "According to your assessment you have few risk factors or previous illnesses.",
            "RiskGroupRed": "According to your assessment you have several underlying diseases or risk factors.",
            "TermQuestion": "Question",
            "TermAnswer": "Answer",
            "QuestionAddYourName": "Your name",
            "AddYourNamePrivacyMessage": "Do you want to add your name, medication or notes to the printout? ",
            "PleaseEnterYourText": "Your name, medication or notes that your doctor should know about:",
            "ButtonYes": "Yes",
            "ButtonNo": "No",
            "ButtonSkip": "Skip",
            "ButtonNext": "Next"
        }
    },
    "ru": {
        "answers": {
            "age00": "0-20 лет",
            "age20": "20-40 лет",
            "age40": "40-60 лет",
            "age60": "60-80 лет",
            "age80": "Больше 14 дней",
            "day14ago": "Больше 14 дней",
            "day1ago": "За посление 24 часа",
            "day3ago": "За последние 7 дней",
            "day7ago": "Дольше 7 дней",
            "fever37": "Нет температуры",
            "fever38": "Выше 38 градусов",
            "fever39": "Выше 39 градусов",
            "maybe": "Возможно",
            "never": "Никогда",
            "no": "Нет",
            "notsure": "Не уверен",
            "yes": "Да"
        },
        "questions": {
            "QuestionSmoker": "Вы курите?",
            "QuestionLung": "У Вас есть подтвержденные врачом заболевания легких?",
            "QuestionDiabetes": "У Вас есть диабет?",
            "QuestionHeart": "У Вас есть сердечные заболевания, подтверждённые врачом?",
            "QuestionAdipositas": "У Вас лишний вес?",
            "QuestionPregnancy": "У Вас лишний вес?",
            "QuestionCortison": "Принимаете препараты с кортизоном?",
            "QuestionImunSuppressiva": "Вы принимаете медикаменты подавляющие имунную систему?",
            "QuestionInfluenzaVaccination": "Прививались от гриппа в последние месяцы?",
            "QuestionArticularRheumatism": "У Вас диагностицирован ревматизм?",
            "QuestionChemotherapy": "Проводится в настоящее время химиотерапия?",
            "QuestionAge": "Ваш возраст?",
            "QuestionContact": "Когда вы контактировали с человеком, позитивно протестированным на COVID-19?",
            "QuestionTravelDaysAgo": "Вы были в последнее время в регионах относящихся к зонам риска?",
            "QuestionFeverLast24h": "У Вас температура?",
            "QuestionFeverLast4d": "У Вас была температура за последние 4 дня?",
            "QuestionChills": "У Вас озноб?",
            "QuestionFatigue": "Вы чувствуете слабость?",
            "QuestionBodyAches": "У Вас боль в суставах?",
            "QuestionDryCough": "У Вас непрерывный кашель?",
            "QuestionRunnyNose": "У Вас более сильный или другой, чем обычно, кашель?",
            "QuestionDiariah": "У Вас диарея?",
            "QuestionSoreThroat": "Болит горло?",
            "QuestionHeadAche": "Болит голова?",
            "QuestionShortBreath": "Вы выдыхаетесь быстрее, чем обычно? (Одышка)",
            "QuestionLossOfSmellTaste": "Вы не чувствуете запах и вкус?",
            "QuestionSneezing": "Вы чихаете?"
        },
        "details": {
            "DetailsQuestionContact": "Контактом является обмен жидкостями организма или нахождение вместе более 15 минут на расстоянии менее 2х метров."
        },
        "survey": {
            "LanguageName": "pусский",
            "BecomeTranslator": "К сожалению анкеты на этом языке нет. Если Вы можете перевести тексты на Ваш язык, обратитесь к нам, пожалуста, через электронную почту _email_.",
            "HeadLine": "Оценка пациентом своего состояния",
            "PreLanguageIntroduction": "Вы инфицированы вирусом COVID-19?\\n\\nАнкета поможет Вам оценить риск заражения. Ваши данные остаются в браузере и строго конфиденциальны. Используйте результаты этой анкеты в формате PDF для беседы с врачом.",
            "LanguageIntroduction": "Ваши данные остаются в браузере и строго конфиденциальны.",
            "DocumentIntroduction": "Данная анкета поможет оценить риск заражения КОВИД-19. Используйте его как руководство для консультации врача.",
            "InfectionRiskHeader": "Симптомы и контакт",
            "InfectionRiskDetails": "Ваша оценка своего самочувствия и контакта с коронавирусом COVID-19.",
            "InfectionRiskGreen": "Похоже, у Вас нет типичных симптомов. Но если Вы чувствуете недомогание, позвоните Вашему врачу. Берегите себя и других.",
            "InfectionRiskYellow": "Наблюдайте за Вашими симптомами. Если Ваше самочувствие ухудшилось или Вы не уверены, позвоните Вашему врачу.",
            "InfectionRiskRed": "Защищайте себя и других людей путем Вашей самоизоляции. Позвоните в местную службу поддержки.",
            "RiskGroupHeader": "Группа риска",
            "RiskGroupDetails": "Оценка состояния Вашего здоровья в свете факторов, связанных с риском заражения коронавирусом COVID-19.",
            "RiskGroupGreen": "По вашей оценке, в настоящее время у вас нет дополнительных рисков. ",
            "RiskGroupYellow": "Согласно вашей оценке, у вас мало факторов риска или предыдущих болезней. ",
            "RiskGroupRed": "Согласно вашей оценке, у вас есть несколько основных заболеваний или факторов риска. ",
            "TermQuestion": "Вопрос",
            "TermAnswer": "Ответ",
            "QuestionAddYourName": "Ваше имя",
            "AddYourNamePrivacyMessage": "Вы хотите добавить свое имя, лекарства или заметки к распечатке? ",
            "PleaseEnterYourText": "Ваше имя, лекарства или заметки, о которых ваш врач должен знать:",
            "ButtonYes": "Да",
            "ButtonNo": "Нет",
            "ButtonSkip": "Пропустить",
            "ButtonNext": "Дальше"
        }
    },
    "de": {
        "answers": {
            "age00": "0-20 Jahre",
            "age20": "20-40 Jahre",
            "age40": "40-60 Jahre",
            "age60": "60-80 Jahre",
            "age80": "über 80 Jahre",
            "day14ago": "vor mehr als 14 Tagen",
            "day1ago": "innerhalb der letzten 24 Stunden",
            "day3ago": "innerhalb der letzten 7 Tage",
            "day7ago": "vor mehr als 7 Tagen",
            "fever37": "kein Fieber",
            "fever38": "über 38° Celsius Fieber",
            "fever39": "über 39° Celsius Fieber",
            "maybe": "vielleicht",
            "never": "nie",
            "no": "nein",
            "notsure": "unsicher",
            "yes": "ja"
        },
        "questions": {
            "QuestionSmoker": "Rauchen Sie?",
            "QuestionLung": "Haben Sie eine ärztlich bestätigte Lungenerkrankung?",
            "QuestionDiabetes": "Haben Sie Diabetes?",
            "QuestionHeart": "Haben Sie eine ärztlich festgestellte Herzerkrankung?",
            "QuestionAdipositas": "Sind Sie sehr übergewichtig?",
            "QuestionPregnancy": "Sind Sie schwanger?",
            "QuestionCortison": "Nehmen Sie derzeit Cortison?",
            "QuestionImunSuppressiva": "Nehmen Sie Medikamente zur Unterdrückung des Immunsystems?",
            "QuestionInfluenzaVaccination": "Wurden Sie in den letzten Monaten gegen Grippe geimpft?",
            "QuestionArticularRheumatism": "Wurde bei Ihnen Rheuma diagnostiziert? ",
            "QuestionChemotherapy": "Erhalten Sie derzeit eine Chemotherapie?",
            "QuestionAge": "Wie alt sind Sie?",
            "QuestionContact": "Wann hatten Sie Kontakt zu einem auf COVID-19 positiv getesteten Menschen?",
            "QuestionTravelDaysAgo": "Waren Sie in der letzten Zeit in einem der Risikogebieten?",
            "QuestionFeverLast24h": "Haben Sie Fieber?",
            "QuestionFeverLast4d": "Hatten Sie in den letzten 4 Tagen Fieber?",
            "QuestionChills": "Haben Sie Schüttelfrost?",
            "QuestionFatigue": "Fühlen Sie sich schlapper als sonst?",
            "QuestionBodyAches": "Haben Sie Gliederschmerzen?",
            "QuestionDryCough": "Haben Sie anhaltenden Husten?",
            "QuestionRunnyNose": "Haben Sie mehr oder anderen Schnupfen als sonst? ",
            "QuestionDiariah": "Haben Sie Durchfall?",
            "QuestionSoreThroat": "Haben Sie Halsschmerzen?",
            "QuestionHeadAche": "Haben Sie Kopfschmerzen?",
            "QuestionShortBreath": "Sind Sie derzeit schneller ausser Atem als sonst?",
            "QuestionLossOfSmellTaste": "Können Sie derzeit nichts riechen oder schmecken?",
            "QuestionSneezing": "Müssen Sie niesen? "
        },
        "details": {
            "DetailsQuestionContact": "Ein Kontakt besteht beim Austausch von Körperflüssigkeiten oder einem Zusammensein von über 15 Minuten mit weniger als 2 Metern Abstand."
        },
        "survey": {
            "LanguageName": "deutsch",
            "BecomeTranslator": "Leider gibt es den Fragebogen noch nicht in dieser Sprache. Wenn Sie Texte von Deutsch oder Englisch in Ihre Sprache übersetzen können, melden Sie sich per _email_ bei uns.",
            "HeadLine": "Patienten-Selbsteinschätzung ",
            "PreLanguageIntroduction": "Haben Sie eine COVID-19-Infektion? \\nDieser Fragebogen hilf Ihnen Ihr Risiko zu bewerten. Ihre Angaben verbleiben im Browser selbst und sind damit privat. Die Ergebnisse dieses Fragebogens im PDF-Format können Sie für ein Arztgespräch verwenden.",
            "LanguageIntroduction": "Ihre Angaben verbleiben im Browser selbst und sind damit privat. ",
            "DocumentIntroduction": "Dieser Fragebogen hilf Ihr Risiko für eine COVID-19-Infektion zu bewerten. Verwenden Sie es als Leitfaden für ein Arztgespräch. ",
            "InfectionRiskHeader": "Symptome und Kontakt",
            "InfectionRiskDetails": "Ihre Einschätzung zu Ihrem aktuellen Gesundheitszustand und Kontakt mit dem Coronavirus COVID-19.",
            "InfectionRiskGreen": "So wie es aussieht, haben Sie derzeit keine der typischen Symptome. Falls Sie sich jedoch unwohl fühlen, rufen Sie Ihren Arzt an. Passen Sie gut auf sich auf und schützen Sie sich und andere.",
            "InfectionRiskYellow": "Schonen Sie sich und beobachten Sie Ihre Symptome. Wenn sich diese verschlimmern oder Sie unsicher sind, rufen Sie Ihren Arzt an.",
            "InfectionRiskRed": "Schützen Sie sich und Ihre Mitmenschen durch Isolation. Rufen Sie ihre lokale Beratungsstelle an.",
            "RiskGroupHeader": "Risikogruppe",
            "RiskGroupDetails": "Ihre Einschätzung zu Ihrem aktuellen Gesundheitszustand in Bezug auf Faktoren, die bei einer Infektion mit dem Coronavirus COVID-19 zusätzliche Risiken darstellen könnten.",
            "RiskGroupGreen": "Laut Ihrer Einschätzung haben Sie derzeit keine zusätzlichen Risiken. ",
            "RiskGroupYellow": "Laut Ihrer Einschätzung haben Sie wenige Risikofaktoren oder Vorerkrankungen. ",
            "RiskGroupRed": "Laut Ihrer Einschätzung haben Sie mehrere Grunderkrankungen oder Risikofaktoren. ",
            "TermQuestion": "Frage",
            "TermAnswer": "Antwort",
            "QuestionAddYourName": "Ihr Name",
            "AddYourNamePrivacyMessage": "Möchten Sie dem Ausdruck Ihren Namen, Medikamente oder Notizen hinzufügen? ",
            "PleaseEnterYourText": "Ihr Name, Medikamente oder Notizen von denen Ihr Arzt wissen sollte:",
            "ButtonYes": "Ja",
            "ButtonNo": "Nein",
            "ButtonSkip": "Überspringen",
            "ButtonNext": "Weiter"
        }
    },
    "fr": {
        "survey": {
            "LanguageName": "français",
            "BecomeTranslator": "Malheureusement, le questionnaire n'est pas encore disponible dans cette langue. Si vous êtes en mesure de traduire des textes de l'allemand\/anglais dans votre langue, veuillez nous contacter par _email_.",
            "HeadLine": "Auto-évaluation du patient",
            "TermQuestion": "Question",
            "TermAnswer": "Réponse",
            "QuestionAddYourName": "Votre nom",
            "ButtonYes": "Oui",
            "ButtonNo": "Non",
            "ButtonNext": "Continue"
        }
    },
    "tr": {
        "survey": {
            "LanguageName": "türkçe",
            "BecomeTranslator": "Ne yazık ki, anket bu dilde henüz mevcut değil. \\nAlmanca veya İngilizce metinleri kendi dilinize çevirebiliyorsanız, _email_ aracılığıyla bize ulaşın.",
            "HeadLine": "Hastanın öz değerlendirmesi"
        }
    },
    "it": {
        "survey": {
            "LanguageName": "italiano",
            "BecomeTranslator": "Purtroppo il questionario non è ancora disponibile in questa lingua. Se è in grado di tradurre testi dal tedesco\/inglese nella sua lingua, la preghiamo di contattarci tramite _email_.",
            "HeadLine": "Autovalutazione del paziente",
            "InfectionRiskHeader": "Sintomi e contatto"
        }
    },
    "es": {
        "survey": {
            "LanguageName": "español",
            "BecomeTranslator": "Lamentablemente, el cuestionario todavía no está disponible en este idioma. Si puede traducir textos del alemán\/inglés a su idioma, por favor, póngase en contacto con nosotros por _email_.",
            "HeadLine": "Autoevaluación del paciente",
            "InfectionRiskHeader": "Síntomas y contacto"
        }
    }
};
